version: "3"
services:
  jupyter_container:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_container
    environment:
     - JUPYTER_TOKEN=tutorial
    ports:
     - "8899:8888"
    volumes: 
     - C:/Users/YOUR_ACCOUNT/Diabetes-HDR-Tutorial-main/notebooks:/home/jovyan/work

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
     - "5434:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=tutorial
    volumes: 
     - C:/Users/YOUR_PATH/Diabetes-HDR-Tutorial-main/tutorial_data:/var/lib/postgresql/data/
